services:
  api:
    build: .
    container_name: churn_api
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: "8000"
      DB_USER: sn_dehghani
      DB_PASS: sndi
      DB_NAME: sn_dehghani
      DB_SCHEMA: public
      FEATURE_TABLE: final_features
      SEQ_LEN: "6"
      ARTIFACT_DIR: /app/artifacts
    ports:
      - "8080:8080"
    volumes:
      - ./notebooks/artifacts:/app/artifacts:ro

